development:
  adapter: postgresql
  database: db/factoor_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: db/factoor_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: db/factoor_production
  pool: 5
  timeout: 5000